
  /*
  - een promptfunctie die een naam vraagt en antwoord op geeft.
  - een functie die uitnodigt een nummer te raden
  - een reactie als het goed is
  een
  
  
  */
  
  
  
  
  
  /// program where the user has to guess a number generated by a program

  Welcome = function (){
    var person = prompt ("Welkom! Wat is je naam?")
    
    if (person != null) {alert("hoi " + person)}
    
    guessNumber()
    
    }


  function guessNumber() {

    // generating a random integer from 0 to 25
    const random = Math.floor(Math.random(25)+1);

    // take input from the user
    let number = parseInt(prompt('raad een nummer van 0 tot 25: '));

    // take the input until the guess is correct
    while(number !== random) {
        number = parseInt(alert('dat is niet correct'));
        prompt("probeer het nog eens")
    }


    // check if the guess is correct
    if(number == random) 
        alert('helemaal goed');
        alert("je hebt een kopje soep gewonnen!")
    }

   

// call the function

Welcome()
